FROM ubuntu
RUN apt-get update \
    && apt-get install -y wget \
    && wget -O bitcoin.tar.gz https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-aarch64-linux-gnu.tar.gz \
    && tar xvzf bitcoin.tar.gz \
    && mv bitcoin-23.0 bitcoin \
    && rm -rf bitcoin.tar.gz \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bitcoin/bin/bitcoind"]
CMD ["-datadir=/data"]
